---
title: "Presentation Final Project"
subtitle: "Moral objections in the workplace"
author: "Sophie Pychlau"
institute: "University of Oregon"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: ["default", "uo", "uo-fonts"]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)

library(reshape2)
library(tidyverse)
library(ggplot2)
library(ggcorrplot)
library(Hmisc)
library(ggsn)
library(qgraph)
library(reactable)
library(here)
library(gt)

here::here

data <- read_csv("data_syn.csv")

```

class: center, middle

#Visualizing correlations

---
First, the data...

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.width=4, fig.height=4}

variable_names <- read_csv("variables2.csv") 

variable_names <- variable_names %>% 
  mutate(Function = as.factor(Function))

data <- read_csv("data_syn.csv") 

descriptives <- data %>% 
  psych::describe() %>% 
  mutate(Acronym = as.factor(vars))

levels(descriptives$Acronym) <-  c("prhvos", "prmvos", "morobs", "guilt", "pride", "emorep", "vofrequ", "prhvoss", "obse", "morobss",
                                   "feeltr", "SER", "selfas", "VoicSat", "frame", "comval", "authov", "corese", "ueprorg", "shame", "constr")

variables <- variable_names %>% 
  left_join(descriptives, by = "Acronym") %>% 
  mutate(Mean = round(mean, 2)) %>% 
  mutate(SD = round(sd, 2))

variables <- variables[, c(1, 3, 2, 18, 19, 4)]

variables %>% 
  gt()

```


---

#Using geom_tile

```{r, echo=FALSE}

cormat <- round(cor(data), 2)

melted_cormat <- melt(cormat)

ggplot(data = melted_cormat, aes(Var2, Var1, fill = value))+
  geom_tile(color = "white") +
  scale_fill_gradient2(low = "#b35806", high = "#542788", mid = "#f7f7f7", 
                      midpoint = 0, limit = c(-1, 1), space = "Lab", 
                      name="Correlation\nstrength") +
  theme_minimal()+ 
  theme(axis.text.x = element_text(angle = 90, vjust = 1, size = 11, hjust = 1)) + 
  coord_fixed() +
  labs(x = "",
       y = "",
       title = "Pearson correlations")

```


---
#Using ggcorrplot package 

```{r, echo=FALSE, message=FALSE}

cormat_pearson <- rcorr(as.matrix(data), type = "pearson")
p.mat <- cormat_pearson$P

ggcorrplot(cormat, method = "square", 
           type = "lower", 
           lab = TRUE,
           lab_size = 2,
           title = "Pearson correlations\nOnly significant (alpha < .05) correlations shown",
           hc.order = TRUE,
           outline.col = "white",
           p.mat = p.mat,
           sig.level = 0.05,
           insig = "blank") + 
  scale_fill_gradient2(low = "#542788", high = "#b35806", mid = "#f7f7f7", 
                      midpoint = 0, limit = c(-1, 1), space = "Lab", 
                      name = "Correlation\nstrength") +
  labs(title = "Correlation matrix using ggcorrplot")

```

---
#Trying a network-like display

```{r, echo=FALSE}

 gqgraph <- qgraph(cormat, 
        graph = "pcor", 
        layout = "circle", 
        minimum = "sig", 
        sampleSize = 99, 
        posCol = c("#ef8a62", "turquoise4"), 
        negCol = c("#67a9cf", "slateblue3"),
        edge.labels = FALSE) 

```

---

If I want to have this printable in black and white, I can make the negative lines dashed

```{r, echo=FALSE}
makeBW(gqgraph, plot = TRUE)
```

